package:
  name: tpstringintpong
  version: 8.96
  description: Malicious package tpstringintpong 
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
  dependencies:
    runtime:
      - python3

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - ca-certificates-bundle
      - busybox
      - gcc
      - musl-dev
      - python3
      - python3-dev
      - py3-pip
      - py3-setuptools
      - py3-virtualenv

pipeline:
  - name: Build tpstringintpong package
    runs: |
      EXECDIR="${{targets.destdir}}/usr/bin"
      WEBAPPDIR="${{targets.destdir}}/usr/share/testapps/tpstringintpong"
      mkdir -p "${EXECDIR}" "${WEBAPPDIR}"
      echo "#!/usr/share/testapps/tpstringintpong/venv/bin/python3" > "${EXECDIR}/tpstringintpong"
      cat setup.py >> "${EXECDIR}/tpstringintpong"
      chmod +x "${EXECDIR}/tpstringintpong"
      virtualenv "${WEBAPPDIR}/venv"
      sh -c "source '${WEBAPPDIR}/venv/bin/activate' && pip install setuptools && python setup.py install"
